### POST register user
POST http://localhost:8000/api/register
Content-Type: application/json

{
  "first_name": "a",
  "last_name": "A",
  "email": "youremail@gmail.com",
  "password": "qwe",
  "password_confirm": "qwe"
}

### POST login user
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "youremail@gmail.com",
  "password": "a"
}

> {% client.global.set("auth_token", response.body.token); %}

### POST refresh token
POST http://localhost:8000/api/refresh

> {% client.global.set("auth_token", response.body.token); %}

### Get user auth
GET http://localhost:8000/api/user
Authorization: Bearer {{auth_token}}

### POST user logout
POST http://localhost:8000/api/logout


### POST forgot password
POST http://localhost:8000/api/forgot
Content-Type: application/json

{
  "email": "youremail@gmail.com"
}

### Get test CORS
GET http://localhost:8000/api/user
Authorization: Bearer {{auth_token}}
Origin: http://localhost:4200
Access-Control-Request-Method: GET

### POST Reset password
POST http://localhost:8000/api/reset/your_reset_password_token
Origin: http://localhost:4200
Access-Control-Request-Method: POST
Content-Type: application/json

{
  "password": "asd",
  "password_confirm": "asd"
}