application:
  frontend-default-url: http://localhost:4200
  security:
    access-token-validity: 20
    refresh-token-validity: 10080
    access-token-secret: ${ACCESS_TOKEN_SECRET}
    refresh-token-secret: ${REFRESH_TOKEN_SECRET}
    allowed-origins: http://localhost:4200,http://localhost:3000,http://localhost:8080
    google-client-id: ${GOOGLE_CLIENT_ID}
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: ${GOOGLE_MAIL_USERNAME}
    password: ${GOOGLE_MAIL_PASSWORD}
    test-connection: true
    properties:
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.debug": true
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: 123
  sql:
    init:
      platform: postgres
      mode: always


server:
  port: 8000
  error:
    include-message: always